### ISSUE TITLE
Failed to import module new_test: No module named 'uvm'

### ISSUE THREAD

**Issue by zfling** [tpoikela/uvm-python#14]
after installed as a package, and runing minimal working example,
there is a problem:
Failed to import module new_test: No module named 'uvm'

![Snipaste_2020-03-22_18-26-15](https://user-images.githubusercontent.com/13745728/77247301-aa6fac80-6c6a-11ea-9c07-eea5afdf303d.png)

what can i do to solve this problem.

**Comment by zfling** [comment]
ln -s ~/uvm/uvm-python/src/uvm uvm

**Comment by tpoikela** [comment]
Hi. Thanks for your interest to uvm-python. I added symlink usage to the example, in case you don't want to install uvm-python. On the other hand, you can use Python3 venv for installation in order to keep your system Python installation clean.

**Comment by aneels3** [comment]
Hi @tpoikela I am getting the same error while running the minimal working example. What could be the possible reason for this? 
![scrrenshot](https://user-images.githubusercontent.com/32580268/80128655-9bef1a80-85b3-11ea-9106-f27b67b77885.png)

**Comment by tpoikela** [comment]
Hi Anil

It should be fixed now in the master branch. Can you retry? Remember to
install uvm-python, or set the PYTHONPATH accordingly, or use the symlink
method.

-Tuomas

**Comment by aneels3** [comment]
Hi, @tpoikela  thanks for the reply. 
I have used the symlink method but didn't work out.
I used this command during installation python -m pip install --user . and didn't created the venv for the same.

Do I need to create the venv?

**Comment by tpoikela** [comment]
Hi Anil

Did you update the git repo? Do you get the same error still? Basically,
the issue was that functions decorated with @cocotb.test() did not have
keyword "async". Can you check that the keywords are there now? The
installation method should not matter. You can use venv if you want, but
your command should also be fine.

-Tuomas

**Comment by aneels3** [comment]
Hi @tpoikela 
The "async" keyword is missing before the function declaration of new_test.py. It is there in the documentation and in the README section but not in the master branch of the repo. I had edited the new_test.py file and added the async keyword before the function declaration and it works fine.

**Comment by tpoikela** [comment]
Hi Anil

You are correct. Sorry, I pushed into wrong remote, not to github. Now it
should be visible, checked from the github page.

-Tuomas
