### ISSUE TITLE
uvm_info

### ISSUE THREAD

**Issue by zfling** [tpoikela/uvm-python#21]
How to save uvm_info into a log file，not only into terminal?

**Comment by tpoikela** [comment]
The API for setting report files is the same as in SystemVerilog. You can do the following:

```python

# In your top test, after all components are created (ie connect_phase):
def connect_phase(self, phase):
    self.f = open("uvm_logfile.txt", "w")
    self.set_report_default_file_hier(self.f)
...
# In your top test, in final_phase:
def final_phase(self, phase):
    self.f.close()  # Without this, nothing is printed to the file, so don't forget it
```

Let me know if it does not work. And look at the [reporting API](https://uvm-python.readthedocs.io/en/latest/base/uvm_component.html#uvm.base.uvm_component.UVMComponent.set_report_default_file_hier). Each component can have its own logfile.

**Comment by zfling** [comment]
I tried and it did not work.

**Comment by tpoikela** [comment]
I forgot that default action is UVM_DISPLAY, so you need to also do (when you set the default file):
```python
self.set_report_severity_action_hier(UVM_INFO, UVM_LOG | UVM_DISPLAY)
```

**Comment by zfling** [comment]
It worked now. Is there a way to save all logs in the terminal to a log file, not only the UVM_INFO, such as compile log, cocotb log...

**Comment by tpoikela** [comment]
Sure. It's not feature of cocotb or uvm-python. Just use shell re-direction:

```
make <args> > run.log
make <args> >& run.log  # This dumps also stderr to run.log
```
will dump everything to run.log.

**Comment by tpoikela** [comment]
I will close this as uvm-python -specific issue was resolved.
