### ISSUE TITLE
UVM Python minimal test

### ISSUE THREAD

**Issue by tsengr0916** [tpoikela/uvm-python#22]
I'm trying to run the minimal test which is the example test that comes with the uvm-python package. When I launch the test, it shows this error:
 
File "/prj/tbs/5g/sandiego/hw/main/users/hctseng/dev5g/prach4/uvm_python/uvm-python-master/test/examples/minimal/uvm/base/uvm_globals.py", line 441, in uvm_is_sim_active  return simulator.is_running()
AttributeError: module 'simulator' has no attribute 'is_running'

Any ideas? I'm using QuestaSim version 2020.2. 

Thanks,
Richard

**Comment by tpoikela** [comment]
Hi Richard

Looks to me that cocotb version is not having `simulation.is_running` available. This should be available in newer cocotb versions. Could you check the version of cocotb you're using? This version should be fine for running uvm-python: https://pypi.org/project/cocotb/1.4.0/

You should also get a working version of cocotb, if you use python venv, and let uvm-python install the dependencies automatically.

You're doing some 5G/PRACH simulations?

**Comment by tsengr0916** [comment]
Thanks Tuomas. I’m using the 1.4.0.dev0 version. Doesn't this version have the simulation.is_running support? 

If not, I will have to merge the latest release into our repo. This could be a big task. The earlier version of cocotb was not stable and had many bugs. So we downloaded it at a certain point of time, made some modifications/enhancements based on our needs, and then checked in into our own database. To merge it again from the public giHub could be some hassle due to the conflicts with our version.

And yes I’m working on the 5G modem design verification. 

Are you the author of the uvm-python? Do you plan to make it available to Accellera so it can be a standard like SystemVerilog and SystemC versions of UVM?

Richard

**Comment by tpoikela** [comment]
Hi Richard

The version `1.4.0.dev0` was used as a name for very long time, if I'm not mistaken. `is_running` was introduced this year, around May I think. I don't have the exact commit available right now.

As a workaround, you can try changing src/uvm/base/uvm_globals.py to use the commented line `return hasattr(cocotb, 'SIM_NAME') instead of is_running, if you don't have that available.

>Are you the author of the uvm-python? Do you plan to make it available to Accellera so it can be a standard like SystemVerilog and SystemC versions of UVM?

Well, it is basically available for them in the github with the same license as original SystemVerilog UVM. I think it is up to Accellera if they want to make it a standard.

-Tuomas

**Comment by tpoikela** [comment]
Did you get it working? Anything else I can help with regarding `uvm-python`?

**Comment by tsengr0916** [comment]
Sorry I have not got a chance to merge the release 1.4.0 version to our repo. I will need to run a full regression across multiple projects/designs in case it doe not break anything. Please close this ticket for now. I can re-open it later if there is still an issue.  Thanks for your help!
Richard

**Comment by tsengr0916** [comment]
The workaround looks good. Tests can be run now Thanks for your help Tuomas!
