### ISSUE TITLE
Bug in uvm_reg_map.py

### ISSUE THREAD

**Issue by sjalloq** [tpoikela/uvm-python#32]
There seems to be a SV-to-Python conversion typo in uvm_reg_map.py where Xget_bus_infoX() is called.  The SV version of this method updates the 4 arguments passed in but the Python version returns a list.  This list should override the parameters that are passed in.  However, n_bits_init is not updated.  I'll create a PR for this but I wanted you to look at how the byte_en is updated.  It seems to be only set if the element_kind is UVM_FIELD.  In the case of UVM_REG, the byte_en is left as -1.  Is this intentional?  Perhaps in the SV world this is treated as a twos complement number which sets all byte enables to 1?

In all methods that call Xget_bus_infoX, the following

```systemverilog
    [map_info, size, lsb, addr_skip] = self.Xget_bus_infoX(rw, map_info, n_bits, lsb, skip)
```
should be modified to:

```systemverilog
    [map_info, n_bits, lsb, skip] = self.Xget_bus_infoX(rw, map_info, n_bits, lsb, skip)
```

And looking at it, there is a difference between do_bus_write and do_bus_read where `n_bits_init` and `n_bits` are used respectively.  I'm assuming these should be the same.

**Comment by sjalloq** [comment]
Actually, just looking at the SV version, the byte_en is defined as:

```systemverilog
// Type: uvm_reg_byte_en_t
//
// 2-state byte_enable value with <`UVM_REG_BYTENABLE_WIDTH> bits
//
typedef  bit unsigned [`UVM_REG_BYTENABLE_WIDTH-1:0]  uvm_reg_byte_en_t ;
```
which means that initialising it to -1 sets all byte enable bits.  I'll fix this is the PR.

**Comment by sjalloq** [comment]
OK, that last push seems to have fixed things.  My write transaction is now getting written by my driver.  I'll start to test more functionality as I progress and shout as I find issues.

**Comment by tpoikela** [comment]
Thanks for the fix for this issue as well! I've now added a function `sv.get_vector_of_ones` to generate a bit vector with all ones of any size.
