### ISSUE TITLE
test uvm-python/test/examples/integrated/ubus/examples  for "read modify write" can not be randomized with the uvm_do_with

### ISSUE THREAD

**Issue by ogheri** [tpoikela/uvm-python#39]
Hi, I ve just installed UVM-python and I was trying the example in

uvm-python/test/examples/integrated/ubus/examples

with

make <ENTER>

it reaches the end and passes and says "UVM_ERROR: 0" and also "UVM_FATAL: 0"

but trying to add constraints in the uvm_do_with sequences in

uvm-python/test/examples/integrated/ubus/examples/ubus_example_master_seq_lib.py

does not lead to them being taken into account..

I have made some (not impressive) progresses if I do what I show in the attached .py python files but nevertheless I get the results also attached here as .vcd file, i.e. I obtain to write at the same address that I read in the 1st step and really to write the "read data plus 1" but then on the 2nd read (which is the 3rd operation, after the "WRITE" of "read   modify write".... I get from this address completely unrelated [data...](url
[ubus_master_seq_lib.py.txt](https://github.com/tpoikela/uvm-python/files/6198890/ubus_master_seq_lib.py.txt)
[ubus_transfer.py.txt](https://github.com/tpoikela/uvm-python/files/6198891/ubus_transfer.py.txt)
[ubus_example_master_seq_lib.py.txt](https://github.com/tpoikela/uvm-python/files/6198894/ubus_example_master_seq_lib.py.txt)
![Snapshot_2021-03-24 17-24-18](https://user-images.githubusercontent.com/47142952/112345980-d41c4300-8cc5-11eb-967e-ab02d731db64.png)

)

may be I am doing something stupid or is this not yet supported completely ?
thx a lot!

**Comment by ogheri** [comment]
Sorry!!! I GOT IT!!!

In ubus_master_seq_lib.py 

I had to do:
class read_byte_seq(ubus_base_sequence):

    def __init__(self, name="read_byte_seq"):
        ubus_base_sequence.__init__(self, name)
        self.start_addr = 0
        #self.rand("start_addr", range((1 << 32) - 1))
        self.rand("start_addr", range(1024))
        self.transmit_delay = 0

    #  constraint transmit_del_ct { (transmit_del <= 10); }


    async def body(self):
        self.req.data = [1234]
        self.req.addr = self.start_addr
        self.req.read_write = READ
        self.req.size = 1
        self.req.error_pos = 1000
        self.req.transmit_delay = self.transmit_delay
        await uvm_do_with(self, self.req, lambda addr,read_write,size: addr == self.start_addr and size == 1 and read_write == READ)


ALSO ASKING for read_write to be a READ or it was sending WRITEs all the time to the master sequence driver to be performed!!
thx and sorry for the waste of time.

**Comment by tpoikela** [comment]
No problem! I'm glad you figured it out. There are still some issues with
`uvm_do_on_with` (it randomizes only UVMSequenceItem, but not UVMSequence),
but I'm working on it, and will add an example to test/examples on the
usage.

-Tuomas

**Comment by ogheri** [comment]
great thx a lot Tuomas and again....congrats thats super cool!!!!

Alex

⁣Ottieni BlueMail per Android ​

Il giorno 25 Mar 2021, 13:16, alle ore 13:16, Tuomas Poikela ***@***.***> ha scritto:
>No problem! I'm glad you figured it out. There are still some issues
>with
>`uvm_do_on_with` (it randomizes only UVMSequenceItem, but not
>UVMSequence),
>but I'm working on it, and will add an example to test/examples on the
>usage.
>
>-Tuomas
>
