### ISSUE TITLE
uvm_do doesn't work

### ISSUE THREAD

**Issue by M0stafaRady** [tpoikela/uvm-python#45]
I can use `uvm_do_with` but when I try `uvm_do`  it fails with 

```
File "uvm/base/sv.py", line 511, in randomize_with
            raise RandomizeError(
                       uvm.base.uvm_exceptions.RandomizeError: randomize_with() failed for kind=READ addr=C2 data=DEADBEEF [] is not a callable object
```

I guess the [] that is passed as constraint is the problem 
https://github.com/tpoikela/uvm-python/blob/fc5f955701b2b56c1fddac195c70cb3ebb9139fe/src/uvm/macros/uvm_sequence_defines.py#L93

when I try and replaced the [] with `lambda: True ` it works.

**Comment by tpoikela** [comment]
Thanks for reporting. Should be now fixed in the master branch.

**Comment by M0stafaRady** [comment]
Thanks
